import { writeFileSync } from "fs";

import axios from "axios";

const apiUrl =
  "http://fonts.google.com/metadata/icons?incomplete=1&key=material_symbols";

const outputFilePath = "src/components/icon/IconTypes.ts";

axios
  .get(apiUrl)
  .then((response) => {
    // The response text starts with a prefix, so we need to remove it
    const data = JSON.parse(response.data.replace(/^\)\]\}'/, ""));

    // Extract all unique icon names
    const iconNames = new Set(
      data.icons.map((icon: { name: string }) => icon.name)
    );

    // Create the content for the TypeScript file
    const fileContent =
      "/** This file is autogenerated. Do not edit it directly.\n" +
      " *  Run 'pnpm update-material-icons' to update it.\n" +
      " */\n" +
      "export type IconTypes =\n" +
      Array.from(iconNames)
        .map((name) => `  | "${name}"`)
        .join("\n") +
      ";\n";

    // Write the content to the file
    writeFileSync(outputFilePath, fileContent);

    console.log(
      `✅ 📜 File '${outputFilePath}' has been updated successfully.`
    );
  })
  .catch((error) => {
    console.error("❗️ Error fetching the icon metadata:", error);
  });
